{% set name = "sphinx-enum-extend" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-enum-extend-{{ version }}.tar.gz
  sha256: af14e540077f961cf3d2279ccfe7b41282378c5342c17bbcb55837de438aa018

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - enum_extend
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - sphinx_enum_extend
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Amourspirit/python-sphinx-enum-extend
  summary: Spinx plugin for documenting enum-extend.AutoEnum
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Amourspirit
