{% set name = "sphinx-enum-extend" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-enum-extend-{{ version }}.tar.gz
  sha256: c0a73ebb106aae3562247244a759c55c731d2204026648501440ceef4166ff97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
    - enum-extend >=0.1.1
    - sphinx
  run:
    - python >=3.4
    - enum-extend >=0.1.1
    - sphinx

test:
  imports:
    - sphinx_enum_extend
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Amourspirit/python-sphinx-enum-extend
  summary: Spinx plugin for documenting enum-extend.AutoEnum
  license: MIT
  license_file: LICENSE
  description: |
    Sphinx Extension for AutoEnum that allows for auto-documenting python enums.
    Extends autodoc in a way that allows for auto generation docs derived from AutoEnum class.
  doc_url: https://python-sphinx-enum-extend.readthedocs.io/
  dev_url: https://github.com/Amourspirit/python-sphinx-enum-extend

extra:
  recipe-maintainers:
    - Amourspirit
